### ISSUE TITLE
It is hoped that the specific parameters of the hard label setting can be obtained.

### ISSUE THREAD

**Issue by xtyXpastor** [lin-tan/disguide#2]
Hello author, sorry to bother you.
I really appreciate your article, it inspires me a lot. Recently, I tried to reproduce the results in the paper, but failed with the hard label setting.
I list the parameters I set as follows:
```bash
cd disguide;

# read -p "Device to use:" device
# read -p "Select hard or soft label, one of [hl,l1]" loss
# echo "Running DisGUIDE on CIFAR10"

dataset=cifar10              # Dataset to run on
loss=hl                      # hl for hard-label, l1 for soft-label
device=2
teacher_arch=resnet34        # Supports resnet34 and resnet18
replay="Classic"             # Standard experience replay. Set to "Off" to disable replay
input_space="post-transform"  # "pre-transform" implies no attacker knowledge. "post-transform" assumes knowledge of image preprocessing
query_budget=8              # Query budget in millions
lr_S=0.03                    # Initial student learning rate
ld=2                         # Set to 2 for cifar10, 04 for cifar100
ri=3                         # Replay training iterations
rs=100                       # Replay size in 10k
grayscale=8                  # Set to 0 to deactivate grayscale, 8 to enable
experiment_type="disguide"   # Whether to run disguide or dfme experiment
ensemble_size=2              # Value must be 2 or higher for DisGUIDE. May be any value for DFME
suffix="${dataset}_SlrS${lrDec}qb${query_budget}st048di1ld0${ld}gs${grayscale}ri${ri}rs${rs}"

python3 train.py --experiment-type ${experiment_type} --epoch-itr 150 --log-interval 30 --d-iter 1 --grayscale ${grayscale} --rep-iter ${ri} --replay-size ${rs}0000  --input-space ${input_space} --lambda-div 0.${ld} --model ${teacher_arch}_8x --step 0.4 0.8 --ckpt checkpoint/teacher/${dataset}-${teacher_arch}_8x.pt --dataset ${dataset} --lr-S ${lr_S} --suffix ${suffix} --replay ${replay} --device ${device} --query-budget ${query_budget} --log-dir save_results/${dataset}  --lr-G 1e-4 --ensemble-size ${ensemble_size} --batch-size 256 --loss ${loss} --student-model ensemble_resnet18_8x;
```

I can only observe about 80% test set accuracy under this parameter. It would be very helpful to me if you could provide a standard hard label learning parameter.
Looking forward to your reply and thank you for your contribution to the model-stealing community.

Yours sincerely,
Tianyu Xia

**Comment by rosenthj** [comment]
80% is lower than any of the runs we had on CIFAR10 HL with 8 million query budget.

The only difference I can see at first glance is that you set the input space to post transform, which I am unsure of the difference in terms of difficulty for this specific problem (I recall we got every so slightly better results , but pre-transform is what we ran our experiments with, as it is more realistic.

The victim model we used for the CIFAR-10 experiments are [publicly available](https://www.dropbox.com/sh/xh9eqq0iknagwwc/AACTQGte7hecIcr-DexD7z9ea?dl=0) and trained by authors of [prior work](https://github.com/VainF/Data-Free-Adversarial-Distillation).

The CIFAR-10 HL runs we had with what should be your exact settings except pre-transform input space, reached 80% after 3.264m, 3.2256m, 3.2256m, 3.7248m, and 2.9952m queries respectively. They hit 85% after 3.84m, 3.84m, 3.456m, 6.4896m, and, 4.416m respectively. The order of these two sets of numbers is consistent, meaning the first run got 80% in 3.264m queries and 85% after 3.84m queries respectively.

As you are reporting significantly lower numbers, I will run a set of experiments to ensure I didn't break the code during refactoring, shortly before code release.

**Comment by xtyXpastor** [comment]
Thank you for your reply, I will also use the link you gave now to download the victim model to retest. The victim model I used before was given in the DFME paper.
Thank you again.

**Comment by rosenthj** [comment]
Those should be the same victim models. DFME paper got the model from that same prior work!

**Comment by xtyXpastor** [comment]
I think so.

**Comment by xtyXpastor** [comment]
Thank you for your reply again !hahahahaha

**Comment by rosenthj** [comment]
I started 2 runs to make sure I didn't break anything in the refactoring just before releasing the code.

These runs are with a fresh clone of the released codebase, so if these don't match up with the results I got I will have to investigate further on my end. However, if these end up in the same ballpark as my prior experiments, I might need some help from you to figure out what is going on.

I wonder if it is possible that pre-transform input space in the HL setting, for whatever reason, actually benefits training somehow?

**Comment by rosenthj** [comment]
So the two runs are not quite done (slightly over 90% completion) yet, but they are outperforming the values reported in the paper at this point, with one model having hit 89.5% and the other model having hit 88.7% accuracy. Could you run your experiments with input_space="pre-transform" and report back whether you are getting in the same ballpark as our reported results?

I will probably run with input_space="post-transform" tomorrow out of curiosity, but really, I don't think those results are too relevant, as the attacker would not have access to the transform, and if they did, they could always choose not to use it for their own model.

**Comment by xtyXpastor** [comment]
Thank you for your reply. I re-run the experiment using the pre-transform setting and got an accuracy result greater than 89%. It seems that the problem is indeed in the choice of pre-transform and post-transform. This is a surprising and interesting phenomenon. I sincerely appreciate your kind help.

**Comment by rosenthj** [comment]
Great! I am glad we figured out the issue, even if it raises some more questions.

I will probably update the readme and scripts in the next few days, to avoid other researchers using post-transform and encountering the same issue.

If you encounter any more issues feel free to either raise a new issue on this repo or send me an email (check the paper if you need the address).

For now, I am closing this thread!
